inputs:

    #
    # Cachix
    #
    # Currently only supports single bucket setup.
    #

    cachix-url:
        required: false
        description: URL of Cachix bucket to use.

    cachix-pubkey:
        required: false
        description: Pubkey of that Cachix bucket

    # extra-substituters:

    # extra-pubkeys:


    #
    # [Intended for internal use]
    #

    __flake_ref:
        default: "nixpkgs/nixos-unstable"
        required: false

    __checkout_path:
        default: "${{ github.workspace }}/spheti-action-checkout"
        required: false

    __this_repo:
        default: "MidAutumnMoon/spheti-action"
        required: false


runs:

    using: composite

    steps:

    -   name: Checkout
        uses: actions/checkout@v4
        with:
            repository: ${{ inputs.__this_repo }}
            path: ${{ inputs.__checkout_path }}

    -   name: Setup nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
            modify-profile: true
            flakehub: false
            extra-conf: |
                # 512MiB in Bytes
                download-buffer-size = 536870912
                auto-optimise-store = false
                always-allow-substitutes = true
            source-tag: "v0.32.3" # BUG https://github.com/DeterminateSystems/nix-installer-action/issues/133


    -   name: Set TMPDIR for nix-daemon
        shell: bash
        run: |
            sudo bash -c "exec ${{ inputs.__checkout_path }}/nix/man.florida tweak-nix-daemon"

    -   name: Add Cachix to substituters
        if: ${{ inputs.cachix-url != '' }}
        shell: bash
        run: |
            [[ "${{ inputs.cachix-pubkey }}" == "" ]] && {
                echo '::error::When "cachix-url" is set, "cachix-pubkey" must also be set.'
                exit 1
            }
            sudo bash -c "exec ${{ inputs.__checkout_path }}/nix/man.florida add-substituter \
                --substituter-url \"${{ inputs.cachix-url }}\" \
                --substituter-pubkey \"${{ inputs.cachix-pubkey }}\" \
            "
            declare -r NIX_USER_CONF="$HOME/.config/nix/nix.conf"
            if [[ -f "$NIX_USER_CONF" ]]; then
                sudo bash -c "exec ${{ inputs.__checkout_path }}/nix/man.florida add-substituter \
                    --nix-conf $HOME/.config/nix/nix.conf \
                    --substituter-url \"${{ inputs.cachix-url }}\" \
                    --substituter-pubkey \"${{ inputs.cachix-pubkey }}\" \
                "
            fi

    -   name: Restart nix-daemon
        shell: bash
        run: |
            sudo systemctl daemon-reload
            sudo systemctl restart nix-daemon

    -   name: Verify setup
        shell: bash
        run: |
            echo "Verify nix still builds"
            nix build \
                --no-link \
                --print-build-logs \
                -f "${{ inputs.__checkout_path }}/nix/fixtures/test-build.nix"
            echo

            echo "Display nix config"
            nix --version
            nix config show
            cat /etc/nix/nix.conf || true
            cat $HOME/.config/nix/nix.conf || true

            echo "Show nix-daemon config"
            sudo systemctl cat nix-daemon
            echo

            echo "Verify nix-daemon is active"
            sudo systemctl is-active nix-daemon

    -   name: Cleanup
        shell: bash
        run: |
            echo "Delete checkout on disk"
            rm -rf "${{ inputs.__checkout_path }}"

# vim: nowrap:
