inputs:
    #
    # Cachix
    #
    # Currently only supports single bucket setup.
    #

    cachix-url:
        required: false
        description: URL of Cachix bucket to use.

    cachix-pubkey:
        required: false
        description: Pubkey of that Cachix bucket

    # extra-substituters:

    # extra-pubkeys:

    #
    # [Intended for internal use]
    #

    __flake_ref:
        default: "nixpkgs/nixos-unstable"
        required: false

    __checkout_path:
        default: "${{ github.workspace }}/spheti-action-checkout"
        required: false

    __this_repo:
        default: "MidAutumnMoon/spheti-action"
        required: false

runs:
    using: composite

    steps:
        - name: Disable AppArmor
          shell: bash
          run: |
              sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
              sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
              sudo aa-teardown || true
              sudo systemctl disable --now apparmor.service

        - name: Freeup spaces
          shell: bash
          run: |
              sudo bash "${{ inputs.__checkout_path }}/nix/freeup.bash" &
              disown

        - name: Checkout
          uses: actions/checkout@v5
          with:
              repository: ${{ inputs.__this_repo }}
              path: ${{ inputs.__checkout_path }}

        - name: Setup Lix
          uses: canidae-solutions/lix-quick-install-action@v3
          with:
              lix_conf: |
                  auto-optimise-store = false
                  always-allow-substitutes = true
                  extra-experimental-features = pipe-operator
                  sandbox-fallback = false

        - name: Add Cachix to substituters
          if: ${{ inputs.cachix-url != '' }}
          shell: bash
          run: |
              [[ "${{ inputs.cachix-pubkey }}" == "" ]] && {
                  echo '::error::When "cachix-url" is set, "cachix-pubkey" must also be set.'
                  exit 1
              }
              declare -r NIX_USER_CONF="$HOME/.config/nix/nix.conf"
              if [[ -f "$NIX_USER_CONF" ]]; then
                  bash -c "exec ${{ inputs.__checkout_path }}/nix/man.florida add-substituter \
                      --nix-conf '$NIX_USER_CONF' \
                      --substituter-url '${{ inputs.cachix-url }}' \
                      --substituter-pubkey '${{ inputs.cachix-pubkey }}'"
              fi

        - name: Verify setup
          shell: bash
          run: |
              echo "Verify nix still builds"
              nix build \
                  --no-link \
                  --print-build-logs \
                  -f "${{ inputs.__checkout_path }}/nix/fixtures/test-build.nix"
              echo

              echo "Display nix config"
              nix --version
              nix config show

        - name: Cleanup
          shell: bash
          run: |
              echo "Delete checkout on disk"
              rm -rf "${{ inputs.__checkout_path }}"

# vim: nowrap:
