[package]
name = "florida"
version = "0.1.0"
edition = "2021"
authors = [ "MidAutumnMoon" ]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
nix-config-parser = "0.2"

[profile.release]
lto = "thin"
strip = "all"
opt-level = "s"
panic = "abort"
