[package]
name = "florida"
version = "0.1.0"
edition = "2021"
authors = [ "MidAutumnMoon" ]

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
nix-config-parser = "0.2.0"

[profile.release]
lto = "thin"
strip = "all"
opt-level = "s"
panic = "abort"
